# Generated by Django 4.2.6 on 2023-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_use', models.DateField(auto_now_add=True)),
                ('CR_number', models.CharField(max_length=50)),
                ('cal_due_date', models.DateField()),
                ('temperature', models.FloatField()),
                ('pin_size', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=100)),
                ('inspector', models.CharField(max_length=100)),
                ('history_record', models.CharField(max_length=1255)),
                ('remark', models.CharField(max_length=1255)),
            ],
        ),
    ]
