# Generated by Django 4.2.6 on 2023-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='history_record',
            field=models.CharField(blank=True, max_length=1255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.CharField(blank=True, max_length=1255),
        ),
    ]
