# Generated by Django 4.2.6 on 2023-10-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_history_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='correction_remark',
            field=models.CharField(blank=True, max_length=1255),
        ),
    ]
